options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Schritt 1: JUnit-Tests ausführen
  - name: 'gcr.io/cloud-builders/mvn'
    args:
      - '-Dtest.reports.dir=/workspace/target/surefire-reports'
      - 'test'

  # Schritt 2: Deployment auf Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'test-pipeline'
      - '--source'
      - '.'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--region'
      - 'us-central1'


